// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opensearch
{
    /// <summary>
    /// Provides an OpenSearch destination, a reusable communication channel for an action, such as email, Slack, or a webhook URL. Please refer to the OpenSearch destination documentation for details.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Opensearch = Pulumi.Opensearch;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         var testDestination = new Opensearch.Destination("testDestination", new Opensearch.DestinationArgs
    ///         {
    ///             Body = @"{
    ///   ""name"": ""my-destination"",
    ///   ""type"": ""slack"",
    ///   ""slack"": {
    ///     ""url"": ""http://www.example.com""
    ///   }
    /// }
    /// 
    /// ",
    ///         });
    ///     }
    /// 
    /// }
    /// ```
    /// 
    /// ## Import
    /// 
    /// # Import by name
    /// 
    /// ```sh
    ///  $ pulumi import opensearch:index/destination:Destination test_destination my-destination
    /// ```
    /// </summary>
    [OpensearchResourceType("opensearch:index/destination:Destination")]
    public partial class Destination : Pulumi.CustomResource
    {
        /// <summary>
        /// The JSON body of the destination.
        /// </summary>
        [Output("body")]
        public Output<string> Body { get; private set; } = null!;


        /// <summary>
        /// Create a Destination resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Destination(string name, DestinationArgs args, CustomResourceOptions? options = null)
            : base("opensearch:index/destination:Destination", name, args ?? new DestinationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Destination(string name, Input<string> id, DestinationState? state = null, CustomResourceOptions? options = null)
            : base("opensearch:index/destination:Destination", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Destination resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Destination Get(string name, Input<string> id, DestinationState? state = null, CustomResourceOptions? options = null)
        {
            return new Destination(name, id, state, options);
        }
    }

    public sealed class DestinationArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The JSON body of the destination.
        /// </summary>
        [Input("body", required: true)]
        public Input<string> Body { get; set; } = null!;

        public DestinationArgs()
        {
        }
    }

    public sealed class DestinationState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The JSON body of the destination.
        /// </summary>
        [Input("body")]
        public Input<string>? Body { get; set; }

        public DestinationState()
        {
        }
    }
}
