// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opensearch
{
    public static class GetDestination
    {
        /// <summary>
        /// `opensearch.Destination` can be used to retrieve the destination object by name.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Opensearch = Pulumi.Opensearch;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var test = Output.Create(Opensearch.GetDestination.InvokeAsync(new Opensearch.GetDestinationArgs
        ///         {
        ///             Name = "my-destination",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetDestinationResult> InvokeAsync(GetDestinationArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetDestinationResult>("opensearch:index/getDestination:getDestination", args ?? new GetDestinationArgs(), options.WithDefaults());

        /// <summary>
        /// `opensearch.Destination` can be used to retrieve the destination object by name.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Opensearch = Pulumi.Opensearch;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var test = Output.Create(Opensearch.GetDestination.InvokeAsync(new Opensearch.GetDestinationArgs
        ///         {
        ///             Name = "my-destination",
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetDestinationResult> Invoke(GetDestinationInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetDestinationResult>("opensearch:index/getDestination:getDestination", args ?? new GetDestinationInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDestinationArgs : Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetDestinationArgs()
        {
        }
    }

    public sealed class GetDestinationInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetDestinationInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetDestinationResult
    {
        public readonly ImmutableDictionary<string, object> Body;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;

        [OutputConstructor]
        private GetDestinationResult(
            ImmutableDictionary<string, object> body,

            string id,

            string name)
        {
            Body = body;
            Id = id;
            Name = name;
        }
    }
}
