// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opensearch
{
    public static class GetHost
    {
        /// <summary>
        /// `opensearch.getHost` can be used to retrieve the host URL for the provider's current cluster.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Opensearch = Pulumi.Opensearch;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var test = Output.Create(Opensearch.GetHost.InvokeAsync(new Opensearch.GetHostArgs
        ///         {
        ///             Active = true,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Task<GetHostResult> InvokeAsync(GetHostArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.InvokeAsync<GetHostResult>("opensearch:index/getHost:getHost", args ?? new GetHostArgs(), options.WithDefaults());

        /// <summary>
        /// `opensearch.getHost` can be used to retrieve the host URL for the provider's current cluster.
        /// 
        /// {{% examples %}}
        /// ## Example Usage
        /// {{% example %}}
        /// 
        /// ```csharp
        /// using Pulumi;
        /// using Opensearch = Pulumi.Opensearch;
        /// 
        /// class MyStack : Stack
        /// {
        ///     public MyStack()
        ///     {
        ///         var test = Output.Create(Opensearch.GetHost.InvokeAsync(new Opensearch.GetHostArgs
        ///         {
        ///             Active = true,
        ///         }));
        ///     }
        /// 
        /// }
        /// ```
        /// {{% /example %}}
        /// {{% /examples %}}
        /// </summary>
        public static Output<GetHostResult> Invoke(GetHostInvokeArgs args, InvokeOptions? options = null)
            => Pulumi.Deployment.Instance.Invoke<GetHostResult>("opensearch:index/getHost:getHost", args ?? new GetHostInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetHostArgs : Pulumi.InvokeArgs
    {
        [Input("active", required: true)]
        public bool Active { get; set; }

        public GetHostArgs()
        {
        }
    }

    public sealed class GetHostInvokeArgs : Pulumi.InvokeArgs
    {
        [Input("active", required: true)]
        public Input<bool> Active { get; set; } = null!;

        public GetHostInvokeArgs()
        {
        }
    }


    [OutputType]
    public sealed class GetHostResult
    {
        public readonly bool Active;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Url;

        [OutputConstructor]
        private GetHostResult(
            bool active,

            string id,

            string url)
        {
            Active = active;
            Id = id;
            Url = url;
        }
    }
}
