// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opensearch
{
    /// <summary>
    /// Provides an OpenSearch security user. Please refer to the OpenSearch Access Control documentation for details.
    /// 
    /// ## Example Usage
    /// 
    /// ```csharp
    /// using Pulumi;
    /// using Opensearch = Pulumi.Opensearch;
    /// 
    /// class MyStack : Stack
    /// {
    ///     public MyStack()
    ///     {
    ///         // Create a user
    ///         var mapper = new Opensearch.User("mapper", new Opensearch.UserArgs
    ///         {
    ///             Username = "app-reasdder",
    ///             Password = "SuperSekret123!",
    ///             Description = "a reader role for our app",
    ///         });
    ///         // And a full user, role and role mapping example:
    ///         var readerRole = new Opensearch.Role("readerRole", new Opensearch.RoleArgs
    ///         {
    ///             RoleName = "app_reader",
    ///             Description = "App Reader Role",
    ///             IndexPermissions = 
    ///             {
    ///                 new Opensearch.Inputs.RoleIndexPermissionArgs
    ///                 {
    ///                     IndexPatterns = 
    ///                     {
    ///                         "app-*",
    ///                     },
    ///                     AllowedActions = 
    ///                     {
    ///                         "get",
    ///                         "read",
    ///                         "search",
    ///                     },
    ///                 },
    ///             },
    ///         });
    ///         var readerUser = new Opensearch.User("readerUser", new Opensearch.UserArgs
    ///         {
    ///             Username = "app-reader",
    ///             Password = @var.Password,
    ///         });
    ///         var readerRolesMapping = new Opensearch.RolesMapping("readerRolesMapping", new Opensearch.RolesMappingArgs
    ///         {
    ///             RoleName = readerRole.Id,
    ///             Description = "App Reader Role",
    ///             Users = 
    ///             {
    ///                 readerUser.Id,
    ///             },
    ///         });
    ///     }
    /// 
    /// }
    /// ```
    /// 
    /// ## Import
    /// 
    /// ```sh
    ///  $ pulumi import opensearch:index/user:User reader app_reader
    /// ```
    /// </summary>
    [OpensearchResourceType("opensearch:index/user:User")]
    public partial class User : Pulumi.CustomResource
    {
        /// <summary>
        /// A map of arbitrary key value string pairs stored alongside of users.
        /// </summary>
        [Output("attributes")]
        public Output<ImmutableDictionary<string, string>?> Attributes { get; private set; } = null!;

        /// <summary>
        /// A list of backend roles.
        /// </summary>
        [Output("backendRoles")]
        public Output<ImmutableArray<string>> BackendRoles { get; private set; } = null!;

        /// <summary>
        /// Description of the user.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The plain text password for the user, cannot be specified with `password_hash`. Some implementations may enforce a
        /// password policy. Invalid passwords may cause a non-descriptive HTTP 400 Bad Request error. For AWS Opensearch domains
        /// "password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one digit,
        /// and one special character".
        /// </summary>
        [Output("password")]
        public Output<string?> Password { get; private set; } = null!;

        /// <summary>
        /// The pre-hashed password for the user, cannot be specified with `password`.
        /// </summary>
        [Output("passwordHash")]
        public Output<string?> PasswordHash { get; private set; } = null!;

        /// <summary>
        /// The name of the security user.
        /// </summary>
        [Output("username")]
        public Output<string> Username { get; private set; } = null!;


        /// <summary>
        /// Create a User resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public User(string name, UserArgs args, CustomResourceOptions? options = null)
            : base("opensearch:index/user:User", name, args ?? new UserArgs(), MakeResourceOptions(options, ""))
        {
        }

        private User(string name, Input<string> id, UserState? state = null, CustomResourceOptions? options = null)
            : base("opensearch:index/user:User", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing User resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static User Get(string name, Input<string> id, UserState? state = null, CustomResourceOptions? options = null)
        {
            return new User(name, id, state, options);
        }
    }

    public sealed class UserArgs : Pulumi.ResourceArgs
    {
        [Input("attributes")]
        private InputMap<string>? _attributes;

        /// <summary>
        /// A map of arbitrary key value string pairs stored alongside of users.
        /// </summary>
        public InputMap<string> Attributes
        {
            get => _attributes ?? (_attributes = new InputMap<string>());
            set => _attributes = value;
        }

        [Input("backendRoles")]
        private InputList<string>? _backendRoles;

        /// <summary>
        /// A list of backend roles.
        /// </summary>
        public InputList<string> BackendRoles
        {
            get => _backendRoles ?? (_backendRoles = new InputList<string>());
            set => _backendRoles = value;
        }

        /// <summary>
        /// Description of the user.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The plain text password for the user, cannot be specified with `password_hash`. Some implementations may enforce a
        /// password policy. Invalid passwords may cause a non-descriptive HTTP 400 Bad Request error. For AWS Opensearch domains
        /// "password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one digit,
        /// and one special character".
        /// </summary>
        [Input("password")]
        public Input<string>? Password { get; set; }

        /// <summary>
        /// The pre-hashed password for the user, cannot be specified with `password`.
        /// </summary>
        [Input("passwordHash")]
        public Input<string>? PasswordHash { get; set; }

        /// <summary>
        /// The name of the security user.
        /// </summary>
        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public UserArgs()
        {
        }
    }

    public sealed class UserState : Pulumi.ResourceArgs
    {
        [Input("attributes")]
        private InputMap<string>? _attributes;

        /// <summary>
        /// A map of arbitrary key value string pairs stored alongside of users.
        /// </summary>
        public InputMap<string> Attributes
        {
            get => _attributes ?? (_attributes = new InputMap<string>());
            set => _attributes = value;
        }

        [Input("backendRoles")]
        private InputList<string>? _backendRoles;

        /// <summary>
        /// A list of backend roles.
        /// </summary>
        public InputList<string> BackendRoles
        {
            get => _backendRoles ?? (_backendRoles = new InputList<string>());
            set => _backendRoles = value;
        }

        /// <summary>
        /// Description of the user.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The plain text password for the user, cannot be specified with `password_hash`. Some implementations may enforce a
        /// password policy. Invalid passwords may cause a non-descriptive HTTP 400 Bad Request error. For AWS Opensearch domains
        /// "password must be at least 8 characters long and contain at least one uppercase letter, one lowercase letter, one digit,
        /// and one special character".
        /// </summary>
        [Input("password")]
        public Input<string>? Password { get; set; }

        /// <summary>
        /// The pre-hashed password for the user, cannot be specified with `password`.
        /// </summary>
        [Input("passwordHash")]
        public Input<string>? PasswordHash { get; set; }

        /// <summary>
        /// The name of the security user.
        /// </summary>
        [Input("username")]
        public Input<string>? Username { get; set; }

        public UserState()
        {
        }
    }
}
