# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from . import _utilities

__all__ = [
    'GetDestinationResult',
    'AwaitableGetDestinationResult',
    'get_destination',
    'get_destination_output',
]

@pulumi.output_type
class GetDestinationResult:
    """
    A collection of values returned by getDestination.
    """
    def __init__(__self__, body=None, id=None, name=None):
        if body and not isinstance(body, dict):
            raise TypeError("Expected argument 'body' to be a dict")
        pulumi.set(__self__, "body", body)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter
    def body(self) -> Mapping[str, Any]:
        return pulumi.get(self, "body")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def name(self) -> str:
        return pulumi.get(self, "name")


class AwaitableGetDestinationResult(GetDestinationResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetDestinationResult(
            body=self.body,
            id=self.id,
            name=self.name)


def get_destination(name: Optional[str] = None,
                    opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetDestinationResult:
    """
    `Destination` can be used to retrieve the destination object by name.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_opensearch as opensearch

    test = opensearch.get_destination(name="my-destination")
    ```
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('opensearch:index/getDestination:getDestination', __args__, opts=opts, typ=GetDestinationResult).value

    return AwaitableGetDestinationResult(
        body=__ret__.body,
        id=__ret__.id,
        name=__ret__.name)


@_utilities.lift_output_func(get_destination)
def get_destination_output(name: Optional[pulumi.Input[str]] = None,
                           opts: Optional[pulumi.InvokeOptions] = None) -> pulumi.Output[GetDestinationResult]:
    """
    `Destination` can be used to retrieve the destination object by name.

    ## Example Usage

    ```python
    import pulumi
    import pulumi_opensearch as opensearch

    test = opensearch.get_destination(name="my-destination")
    ```
    """
    ...
