// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opensearch.Outputs
{

    [OutputType]
    public sealed class RoleTenantPermission
    {
        public readonly ImmutableArray<string> AllowedActions;
        public readonly ImmutableArray<string> TenantPatterns;

        [OutputConstructor]
        private RoleTenantPermission(
            ImmutableArray<string> allowedActions,

            ImmutableArray<string> tenantPatterns)
        {
            AllowedActions = allowedActions;
            TenantPatterns = tenantPatterns;
        }
    }
}
