// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opensearch.Outputs
{

    [OutputType]
    public sealed class RoleIndexPermission
    {
        public readonly ImmutableArray<string> AllowedActions;
        public readonly string? DocumentLevelSecurity;
        public readonly ImmutableArray<string> FieldLevelSecurities;
        public readonly ImmutableArray<string> IndexPatterns;
        public readonly ImmutableArray<string> MaskedFields;

        [OutputConstructor]
        private RoleIndexPermission(
            ImmutableArray<string> allowedActions,

            string? documentLevelSecurity,

            ImmutableArray<string> fieldLevelSecurities,

            ImmutableArray<string> indexPatterns,

            ImmutableArray<string> maskedFields)
        {
            AllowedActions = allowedActions;
            DocumentLevelSecurity = documentLevelSecurity;
            FieldLevelSecurities = fieldLevelSecurities;
            IndexPatterns = indexPatterns;
            MaskedFields = maskedFields;
        }
    }
}
