// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface AuditConfigAudit {
    disabledRestCategories?: pulumi.Input<pulumi.Input<string>[]>;
    disabledTransportCategories?: pulumi.Input<pulumi.Input<string>[]>;
    enableRest?: pulumi.Input<boolean>;
    enableTransport?: pulumi.Input<boolean>;
    excludeSensitiveHeaders?: pulumi.Input<boolean>;
    ignoreRequests?: pulumi.Input<pulumi.Input<string>[]>;
    ignoreUsers?: pulumi.Input<pulumi.Input<string>[]>;
    logRequestBody?: pulumi.Input<boolean>;
    resolveBulkRequests?: pulumi.Input<boolean>;
    resolveIndices?: pulumi.Input<boolean>;
}

export interface AuditConfigCompliance {
    enabled?: pulumi.Input<boolean>;
    externalConfig?: pulumi.Input<boolean>;
    internalConfig?: pulumi.Input<boolean>;
    readIgnoreUsers?: pulumi.Input<pulumi.Input<string>[]>;
    readMetadataOnly?: pulumi.Input<boolean>;
    readWatchedFields?: pulumi.Input<pulumi.Input<inputs.AuditConfigComplianceReadWatchedField>[]>;
    writeIgnoreUsers?: pulumi.Input<pulumi.Input<string>[]>;
    writeLogDiffs?: pulumi.Input<boolean>;
    writeMetadataOnly?: pulumi.Input<boolean>;
    writeWatchedIndices?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface AuditConfigComplianceReadWatchedField {
    fields: pulumi.Input<pulumi.Input<string>[]>;
    index: pulumi.Input<string>;
}

export interface RoleIndexPermission {
    allowedActions?: pulumi.Input<pulumi.Input<string>[]>;
    documentLevelSecurity?: pulumi.Input<string>;
    fieldLevelSecurities?: pulumi.Input<pulumi.Input<string>[]>;
    indexPatterns?: pulumi.Input<pulumi.Input<string>[]>;
    maskedFields?: pulumi.Input<pulumi.Input<string>[]>;
}

export interface RoleTenantPermission {
    allowedActions?: pulumi.Input<pulumi.Input<string>[]>;
    tenantPatterns?: pulumi.Input<pulumi.Input<string>[]>;
}
