// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface AuditConfigAudit {
    disabledRestCategories?: string[];
    disabledTransportCategories?: string[];
    enableRest?: boolean;
    enableTransport?: boolean;
    excludeSensitiveHeaders?: boolean;
    ignoreRequests?: string[];
    ignoreUsers?: string[];
    logRequestBody?: boolean;
    resolveBulkRequests?: boolean;
    resolveIndices?: boolean;
}

export interface AuditConfigCompliance {
    enabled?: boolean;
    externalConfig?: boolean;
    internalConfig?: boolean;
    readIgnoreUsers?: string[];
    readMetadataOnly?: boolean;
    readWatchedFields?: outputs.AuditConfigComplianceReadWatchedField[];
    writeIgnoreUsers?: string[];
    writeLogDiffs?: boolean;
    writeMetadataOnly?: boolean;
    writeWatchedIndices?: string[];
}

export interface AuditConfigComplianceReadWatchedField {
    fields: string[];
    index: string;
}

export interface RoleIndexPermission {
    allowedActions?: string[];
    documentLevelSecurity?: string;
    fieldLevelSecurities?: string[];
    indexPatterns?: string[];
    maskedFields?: string[];
}

export interface RoleTenantPermission {
    allowedActions?: string[];
    tenantPatterns?: string[];
}

