// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Opensearch.Inputs
{

    public sealed class RoleIndexPermissionGetArgs : Pulumi.ResourceArgs
    {
        [Input("allowedActions")]
        private InputList<string>? _allowedActions;
        public InputList<string> AllowedActions
        {
            get => _allowedActions ?? (_allowedActions = new InputList<string>());
            set => _allowedActions = value;
        }

        [Input("documentLevelSecurity")]
        public Input<string>? DocumentLevelSecurity { get; set; }

        [Input("fieldLevelSecurities")]
        private InputList<string>? _fieldLevelSecurities;
        public InputList<string> FieldLevelSecurities
        {
            get => _fieldLevelSecurities ?? (_fieldLevelSecurities = new InputList<string>());
            set => _fieldLevelSecurities = value;
        }

        [Input("indexPatterns")]
        private InputList<string>? _indexPatterns;
        public InputList<string> IndexPatterns
        {
            get => _indexPatterns ?? (_indexPatterns = new InputList<string>());
            set => _indexPatterns = value;
        }

        [Input("maskedFields")]
        private InputList<string>? _maskedFields;
        public InputList<string> MaskedFields
        {
            get => _maskedFields ?? (_maskedFields = new InputList<string>());
            set => _maskedFields = value;
        }

        public RoleIndexPermissionGetArgs()
        {
        }
    }
}
