// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * `opensearch.Destination` can be used to retrieve the destination object by name.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as opensearch from "@pulumi/opensearch";
 *
 * const test = pulumi.output(opensearch.getDestination({
 *     name: "my-destination",
 * }));
 * ```
 */
export function getDestination(args: GetDestinationArgs, opts?: pulumi.InvokeOptions): Promise<GetDestinationResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("opensearch:index/getDestination:getDestination", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDestination.
 */
export interface GetDestinationArgs {
    name: string;
}

/**
 * A collection of values returned by getDestination.
 */
export interface GetDestinationResult {
    readonly body: {[key: string]: any};
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
}

export function getDestinationOutput(args: GetDestinationOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDestinationResult> {
    return pulumi.output(args).apply(a => getDestination(a, opts))
}

/**
 * A collection of arguments for invoking getDestination.
 */
export interface GetDestinationOutputArgs {
    name: pulumi.Input<string>;
}
