// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * `opensearch.getHost` can be used to retrieve the host URL for the provider's current cluster.
 *
 * ## Example Usage
 *
 * ```typescript
 * import * as pulumi from "@pulumi/pulumi";
 * import * as opensearch from "@pulumi/opensearch";
 *
 * const test = pulumi.output(opensearch.getHost({
 *     active: true,
 * }));
 * ```
 */
export function getHost(args: GetHostArgs, opts?: pulumi.InvokeOptions): Promise<GetHostResult> {
    if (!opts) {
        opts = {}
    }

    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
    return pulumi.runtime.invoke("opensearch:index/getHost:getHost", {
        "active": args.active,
    }, opts);
}

/**
 * A collection of arguments for invoking getHost.
 */
export interface GetHostArgs {
    active: boolean;
}

/**
 * A collection of values returned by getHost.
 */
export interface GetHostResult {
    readonly active: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly url: string;
}

export function getHostOutput(args: GetHostOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetHostResult> {
    return pulumi.output(args).apply(a => getHost(a, opts))
}

/**
 * A collection of arguments for invoking getHost.
 */
export interface GetHostOutputArgs {
    active: pulumi.Input<boolean>;
}
